theme: cosmo
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition

site_name: Yob User Manual
copyright: 'Copyright © 2016 Tanner Nielsen, Jordan Hendrickson'
pages:
- Home: 'index.md'
- Tutorials:
    - 'Getting Started': 'tutorials/getting_started.md'
    - 'Getting Familar': 'tutorials/getting_familiar.md'
    - 'Advanced Data Sets': 'tutorials/advanced_data_sets.md'
    - 'Advanced Curve Fits': 'tutorials/advanced_curve_fits.md'
    - 'Labeling and Sizing Your Graph': 'tutorials/labeling_and_sizing_your_graph.md'
    - 'Styling Your Graph': 'tutorials/styling_your_graph.md'
- References:
    - 'Storage and Loading Reference': 'references/storage_and_loading_reference.md'
    - 'Expression Reference': 'references/expression_reference.md'
    - 'Curve Fit Reference': 'references/curve_fit_reference.md'
    - 'Calculated Column Reference': 'references/calculated_column_reference.md'
- About: 'about.md'
