site_name: Yob User Manual
theme: cosmo
pages:
- Home: 'index.md'
- Tutorials:
    - 'Getting Started': 'tutorials/getting_started.md'
    - 'Using Calculated Columns': 'tutorials/calculated_columns.md'
- Reference: 'reference.md'
- About: 'about.md'
