site_name: Yob User Manual
theme: cosmo
extra_css:
  - css/extra.css
pages:
- Home: 'index.md'
- Tutorials:
    - 'Getting Started': 'tutorials/getting_started.md'
    - 'Using Calculated Columns': 'tutorials/calculated_columns.md'
- References:
    - 'General Reference': 'references/reference.md'
    - 'Data Storage': 'references/data_storage.md'
- About: 'about.md'
