site_name: Yob User Manual
theme: cosmo
extra_css:
  - css/extra.css
pages:
- Home: 'index.md'
- Tutorials:
    - 'Getting Started': 'tutorials/getting_started.md'
    - 'Getting Familar': 'tutorials/getting_familiar.md'
    - 'Advanced Data Sets': 'tutorials/advanced_data_sets.md'
    - 'Advanced Curve Fits': 'tutorials/advanced_curve_fits.md'
    - 'Labeling and Sizing Your Graph': 'tutorials/labeling_and_sizing_your_graph.md'
    - 'Styling Your Graph': 'tutorials/styling_your_graph.md'
- References:
    - 'General Reference': 'references/reference.md'
    - 'Data Storage': 'references/data_storage.md'
    - 'Calculated Columns': 'references/calculated_columns.md'
- About: 'about.md'
